# Generated by Django 5.0.1 on 2025-02-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_exam',
        ),
    ]
