# Generated by Django 5.0.1 on 2025-02-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='College',
        ),
    ]
