# Generated by Django 5.0.1 on 2025-02-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myexamcenter',
            options={'ordering': ['city']},
        ),
    ]
